version: "3.7"

services:
  webapp2:
    image: 365522784498.dkr.ecr.eu-west-3.amazonaws.com/oz-app2:latest
    networks:
      - traefik-public
    environment:
      - WEB_DOMAIN=web2.andyrum.com
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "128M"
        # reservations:
        #   cpus: "0.1"
        #   memory: 128M
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.web2-http.rule=Host(`${WEB_DOMAIN?Variable not set}`)
        - traefik.http.routers.web2-http.entrypoints=http
        - traefik.http.routers.web2-http.middlewares=https-redirect
        - traefik.http.routers.web2-https.rule=Host(`${WEB_DOMAIN?Variable not set}`)
        - traefik.http.routers.web2-https.entrypoints=https
        - traefik.http.routers.web2-https.tls=true
        - traefik.http.routers.web2-https.tls.certresolver=le
        - traefik.http.services.web2.loadbalancer.server.port=3000

  web:
    image: 365522784498.dkr.ecr.eu-west-3.amazonaws.com/oz-webapp:latest
    networks:
      - traefik-public
    environment:
      - WEB_DOMAIN=web.andyrum.com
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "128M"
        # reservations:
        #   cpus: "0.1"
        #   memory: 128M
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.web-http.rule=Host(`${WEB_DOMAIN?Variable not set}`)
        - traefik.http.routers.web-http.entrypoints=http
        - traefik.http.routers.web-http.middlewares=https-redirect
        - traefik.http.routers.web-https.rule=Host(`${WEB_DOMAIN?Variable not set}`)
        - traefik.http.routers.web-https.entrypoints=https
        - traefik.http.routers.web-https.tls=true
        - traefik.http.routers.web-https.tls.certresolver=le
        - traefik.http.services.web.loadbalancer.server.port=3000

networks:
  traefik-public:
    external: true
